[default]
address = "0.0.0.0"
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true


[default.databases.sqlx]
url = "/home/george/git/good_soup/db/db.sqlite"

[global.databases]
sqlite_db = { url = "db.sqlite" }
