[default]
address = "192.168.0.81"
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true


[global.databases.users]
url = "mysql://remote@192.168.0.84/USERS"
