[default]
address = "0.0.0.0"
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true

[default.databases.users]
url = "db.sqlite"

#[default.databases.test]
#url = "database.sqlite"


#[default.databases.accounts]
#url = "database.sqlite"
